module.exports = {
  exhortTestSubjectUserId: 129586119,
  hoursToWaitBetweenRepliesToSameUser: 38.5,
  maxAttemptsToReplyPerUserPerRun: 1,
  falsePositivesList: [
    'http',
    'haha',
    'adv',
    'san'
  ],
  buzzkillBlacklist: [
    'Negro',
    'Negroes',
    'chink',
    'chinks',
    'gook',
    'gooks',
    'nigger',
    'niggers',
    'nigga',
    'niggas',
    'spic',
    'spics',
    'rape',
    'rapes',
    'rapist',
    'rapists',
    'bombing',
    'bombings',
    'shootings',
    'shooting'
  ],
  tragedyModeBlacklist: [
    'Gaza',
    'Israel',
    'Palestine',
    'invasion',
    'horror',
    'genocide',
    'explosion',
    'assault',
    'Hamas',
    'bomb',
    'plane',
    'death',
    'missile',
    'crash',
    'passenger',
    'suicide',
    'airstrike',
    'brigadier',
    'IDF',
    'ISIS',
    'mourner',
    'mourners',
    'rebel',
    'Iraq',
    'accident',
    'ebola'
  ],
  tragedyHappenedRecently: true,
  maxCommonnessForReplyTopic: [20, 44]
};
