module.exports = {
  exhortTestSubjectUserId: 129586119,
  hoursToWaitBetweenRepliesToSameUser: 36,
  maxAttemptsToReplyPerUserPerRun: 1,
  tragedyHappenedRecently: true,
  maxCommonnessForReplyTopic: [20, 70],
  maxCommonnessForSecondaryTopic: [50, 100],
  maxCommonnessForImageTopic: [500, 3000],
  emojiThresholdPercentage: 5,
  enableImageAnalysis: false,
  visionDonors: [
    '@sterex',
    // 'Andy Moran',
    '@gaski',
    '@im_a_radish',
    '@swizzard',
    '@MetaRantz',
    '@wjjjjt',
    // 'Jayne Fox',
    '@trodrigues',
    '@bryrnff',
    '@kellan',
    // A Boy Named Boom,
    '@jp10k',
    '@inky',
    '@sonyaellenmann',
    '@Merc_Rustad',
    '@ashesinyourhair',
    '@beaugunderson',
    '@mykola',
    '@hatstand4510',
    '@catvalente',
    '@twiddlekins',
    '@outlawpoet',
    '@argumatronic'
  ],
  w2vNeighborChance: 30
};
