var emoji = require('node-emoji');
var probable = require('probable');
var _ = require('lodash');

var boringEmoji = {
  '100': '💯',
  '1234': '🔢',
  currency_exchange: '💱',
  stuck_out_tongue: '😛',
  no_pedestrians: '🚷',
  pisces: '♓️',
  six_pointed_star: '🔯',
  signal_strength: '📶',
  expressionless: '😑',
  us: '🇺🇸',
  wink: '😉',
  kissing_closed_eyes: '😚',
  confused: '😕',
  yum: '😋',
  relieved: '😌',
  arrows_counterclockwise: '🔄',
  mobile_phone_off: '📴',
  es: '🇪🇸',
  flushed: '😳',
  cl: '🆑',
  stuck_out_tongue_closed_eyes: '😝',
  ab: '🆎',
  wc: '🚾',
  mens: '🚹',
  blush: '😊',
  cry: '😢',
  capricorn: '♑️',
  part_alternation_mark: '〽️',
  angry: '😠',
  wheelchair: '♿️',
  rage: '😡',
  abc: '🔤',
  v: '✌️',
  passport_control: '🛂',
  no_mouth: '😶',
  congratulations: '㊗️',
  white_check_mark: '✅',
  u6e80: '🈵',
  up: '🆙',
  point_down: '👇',
  bangbang: '‼️',
  persevere: '😣',
  libra: '♎️',
  '+1': '👍',
  'non-potable_water': '🚱',
  u5408: '🈴',
  open_mouth: '😮',
  m: 'Ⓜ️',
  '-1': '👎',
  smiley_cat: '😺',
  arrow_heading_down: '⤵️',
  cn: '🇨🇳',
  aries: '♈️',
  sweat_smile: '😅',
  jp: '🇯🇵',
  scream: '😱',
  cool: '🆒',
  top: '🔝',
  hash: '#️⃣',
  u6307: '🈯️',
  new: '🆕',
  back: '🔙',
  fearful: '😨',
  ru: '🇷🇺',
  cinema: '🎦',
  restroom: '🚻',
  keycap_ten: '🔟',
  no_mobile_phones: '📵',
  abcd: '🔡',
  imp: '👿',
  scorpius: '♏️',
  negative_squared_cross_mark: '❎',
  atm: '🏧',
  underage: '🔞',
  u6709: '🈶',
  it: '🇮🇹',
  sagittarius: '♐️',
  astonished: '😲',
  sun_with_face: '🌞',
  five: '5️⃣',
  heart_eyes: '😍',
  mask: '😷',
  frowning: '😦',
  laughing: '😆',
  left_luggage: '🛅',
  kissing_smiling_eyes: '😙',
  do_not_litter: '🚯',
  sweat: '😓',
  anguished: '😧',
  information_source: 'ℹ️',
  gemini: '♊️',
  ideograph_advantage: '🉐',
  gb: '🇬🇧',
  accept: '🉑',
  two: '2️⃣',
  chart: '💹',
  point_left: '👈',
  nine: '9️⃣',
  no_bicycles: '🚳',
  smile: '😄',
  end: '🔚',
  worried: '😟',
  six: '6️⃣',
  ng: '🆖',
  repeat_one: '🔂',
  baggage_claim: '🛄',
  zero: '0️⃣',
  no_smoking: '🚭',
  u7533: '🈸',
  kissing_heart: '😘',
  virgo: '♍️',
  fr: '🇫🇷',
  free: '🆓',
  joy: '😂',
  b: '🅱',
  pensive: '😔',
  tired_face: '😫',
  dizzy_face: '😵',
  sunglasses: '😎',
  baby_symbol: '🚼',
  seven: '7️⃣',
  a: '🅰',
  fast_forward: '⏩',
  u7a7a: '🈳',
  neutral_face: '😐',
  unamused: '😒',
  soon: '🔜',
  sob: '😭',
  kr: '🇰🇷',
  ok: '🆗',
  three: '3️⃣',
  ophiuchus: '⛎',
  o2: '🅾',
  customs: '🛃',
  leo: '♌️',
  u5272: '🈹',
  smirk: '😏',
  question: '❓',
  sos: '🆘',
  one: '1️⃣',
  o: '⭕️',
  smiley: '😃',
  vibration_mode: '📳',
  put_litter_in_its_place: '🚮',
  id: '🆔',
  hushed: '😯',
  symbols: '🔣',
  grinning: '😀',
  grin: '😁',
  four: '4️⃣',
  no_entry: '⛔️',
  woman: '👩',
  four_leaf_clover: '🍀',
  waning_gibbous_moon: '🌖',
  x: '❌',
  koko: '🈁',
  heart_decoration: '💟',
  innocent: '😇',
  rewind: '⏪',
  disappointed: '😞',
  vs: '🆚',
  disappointed_relieved: '😥',
  grey_exclamation: '❕',
  weary: '😩',
  parking: '🅿️',
  triumph: '😤',
  taurus: '♉️',
  sa: '🈂',
  cancer: '♋️',
  stuck_out_tongue_winking_eye: '😜',
  sleeping: '😴',
  kissing: '😗',
  loop: '➿',
  capital_abcd: '🔠',
  aquarius: '♒️',
  u7121: '🈚️',
  u6708: '🈷',
  de: '🇩🇪',
  repeat: '🔁',
  confounded: '😖'
};

function getRandomTopicEmoji() {
  var emojiKey = probable.pickFromArray(getEmojiKeysForTopics());
  return emoji.get(emojiKey);
}

var emojiKeysForTopics;

function getEmojiKeysForTopics() {
  if (!emojiKeysForTopics) {
    emojiKeysForTopics = Object.keys(emoji.emoji)
      .filter(emojiKeyIsOKAsATopic);
  }
  return emojiKeysForTopics;
}

function emojiKeyIsOKAsATopic(key) {
  return key.indexOf('arrow') === -1 &&
    !(key in boringEmoji);
}

function emojiValueIsOKAsATopic(value) {
  var isInBoringEmoji = _.some(boringEmoji, 
    function valueMatches(boringValue) {
      return boringValue === value;
    }
  );
  return !isInBoringEmoji;
}

module.exports = {
  getRandomTopicEmoji: getRandomTopicEmoji,
  emojiValueIsOKAsATopic: emojiValueIsOKAsATopic
};
